name: trends
description: Production-grade e-commerce platform built with Flutter and Firebase.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client
  bloc: ^9.2.0
  cloud_firestore: ^6.5.0
  equatable: ^2.0.7
  firebase_analytics: ^12.4.2
  firebase_auth: ^6.5.2
  firebase_authentication_client:
    path: packages/firebase_authentication_client
  firebase_core: ^4.10.0
  firebase_crashlytics: ^5.2.3
  firebase_storage: ^13.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.8.0
  go_router: ^14.8.1
  google_sign_in: ^6.3.0
  persistent_storage:
    path: packages/persistent_storage
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^4.0.1
  firebase_auth_mocks: ^0.15.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
