name: firebase_authentication_client
description: Firebase Authentication implementation of AuthenticationClient.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^6.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  firebase_auth_mocks: ^0.15.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
